### ISSUE TITLE
How can we exclude API groups and resources?

### ISSUE THREAD

**Issue by vikas027** [coopernetes/kube-role-gen#13]
Thanks for writing this handy tool. I am just trying to create a role with some exceptions (say not have `get` in `secrets` resource).

Is this doable? If not, can you please take this as a feature request.

**Comment by vikas027** [comment]
Hey @coopernetes ,

I have updated the code to have the same along with some minor updates. My code works fine :) but my skills are very limited in Go :(. Is it okay if I raise a PR?

**Comment by coopernetes** [comment]
Hi @vikas027,
Absolutely! Feel free to raise a PR. I haven't had a chance to revisit some of the open issues here but would gladly accept contributions to help close them out.

**Comment by coopernetes** [comment]
After having some time to think on this, I think piping the output of kube-role-gen into something like [jq](https://stedolan.github.io/jq/) is probably the way to go if a role needs to be pruned back. The whole point of this util was to generate a complete object that contains every resource + subresource type so I'm less motivated to add this sort of feature. It's not intended to be a full-blown 

Since #8 is fixed, you can do something like the following:

```
$ kube-role-gen -o json | \
  jq -r 'del( .rules[] | select( (.resources[] | contains("secrets")) and (.verbs[] | contains("get")) ) )'
```
