### ISSUE TITLE
Implement read-only flag

### ISSUE THREAD

**Issue by henrysachs** [coopernetes/kube-role-gen#19]
Hey There, 

first of all nice tool! 
second of all 😅
I would love to have a flag like `--read-only` that minimizes the resulting role to only include `get, watch, list` verbs.
Is something like that possible? I haven't took a look at the code already.

**Comment by coopernetes** [comment]
I'm generally opposed to adding this functionality into kube-role-gen since there are better tools available for this sort of post-processing such as [jq]((https://stedolan.github.io/jq/)) or [yq](https://github.com/mikefarah/yq). See below workaround for creating a "read-only" role by piping the output of `kube-role-gen -json` to `jq`.

```shell
kube-role-gen -json | jq 'del(.rules[].verbs[] |           
select((. == "create") or (. == "delete") or (. == "deletecollection") or (. == "patch") or (. == "update")))'
```

If you want to retain the YAML, it's pretty straight-forward to pipe it again to something like PyYAML:
```shell
kube-role-gen -json | jq 'del(.rules[].verbs[] |           
select((. == "create") or (. == "delete") or (. == "deletecollection") or (. == "patch") or (. == "update")))' | \
python3 -c 'import yaml;import json;import sys;print(yaml.dump(json.loads(sys.stdin.read())))'
```
